# Generated by Django 5.2.15 on 2026-06-23 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('UTRMC_ADMIN_ACCESS', 'UTRMC Admin Access'), ('SUPPORT_STAFF_ACCESS', 'Support Staff Access'), ('DATA_ENTRY_ACCESS', 'Data Entry Access'), ('AUDITOR_ACCESS', 'Auditor Access'), ('DEPARTMENT_ADMIN_ACCESS', 'Department Admin Access')], max_length=50)),
                ('scope_type', models.CharField(choices=[('GLOBAL', 'Global Scope'), ('INSTITUTION', 'Institution Scope'), ('TRAINING_SITE', 'Training Site Scope'), ('DEPARTMENT', 'Department Scope'), ('PROGRAM', 'Program Scope'), ('SPECIALTY', 'Specialty Scope')], default='GLOBAL', max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments', to='masters.department')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments', to='masters.institution')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments', to='masters.program')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments', to='masters.specialty')),
                ('training_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments', to='masters.trainingsite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
