# Generated by Django 5.2.15 on 2026-06-23 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, default='', max_length=255)),
                ('qualification', models.CharField(blank=True, default='', max_length=255)),
                ('pmdc_number', models.CharField(blank=True, help_text='Pakistan Medical & Dental Council registration number', max_length=50, null=True, unique=True)),
                ('specialty_name', models.CharField(blank=True, default='', max_length=255)),
                ('subspecialty_name', models.CharField(blank=True, default='', max_length=255)),
                ('institution_name', models.CharField(blank=True, default='', max_length=255)),
                ('department_name', models.CharField(blank=True, default='', max_length=255)),
                ('program_name', models.CharField(blank=True, default='', max_length=255)),
                ('primary_office_phone', models.CharField(blank=True, default='', max_length=50)),
                ('primary_office_phone_normalized', models.CharField(blank=True, default='', max_length=50)),
                ('alternate_phone', models.CharField(blank=True, default='', max_length=50)),
                ('alternate_phone_normalized', models.CharField(blank=True, default='', max_length=50)),
                ('official_email', models.EmailField(blank=True, help_text='Official institutional email', max_length=254, null=True, unique=True)),
                ('room_or_office', models.CharField(blank=True, default='', max_length=100)),
                ('availability_notes', models.TextField(blank=True, default='')),
                ('supervision_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('RETIRED', 'Retired'), ('TRANSFERRED', 'Transferred'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive'), ('UNKNOWN', 'Unknown')], default='ACTIVE', max_length=50)),
                ('max_active_residents', models.PositiveIntegerField(default=5)),
                ('can_supervise_thesis', models.BooleanField(default=False)),
                ('can_supervise_clinical_training', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_supervisors', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supervisors', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_supervisors', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='The linked User account representing identity and credentials', on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
