# Generated by Django 5.2.15 on 2026-06-23 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('supervisors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorprofile',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisors', to='masters.department'),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='designation_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisors', to='masters.designation'),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='institution_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisors', to='masters.institution'),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='program_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisors', to='masters.program'),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='specialty_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisors', to='masters.specialty'),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='training_site_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisors', to='masters.trainingsite'),
        ),
    ]
