# Generated by Django 5.2.15 on 2026-06-23 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, default='', max_length=255)),
                ('cnic_or_passport', models.CharField(help_text='Unique national identification number (CNIC or Passport)', max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('primary_phone', models.CharField(blank=True, default='', max_length=50)),
                ('primary_phone_normalized', models.CharField(blank=True, default='', max_length=50)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=50)),
                ('whatsapp_number_normalized', models.CharField(blank=True, default='', max_length=50)),
                ('alternate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('program_name', models.CharField(blank=True, default='', max_length=255)),
                ('specialty_name', models.CharField(blank=True, default='', max_length=255)),
                ('training_level', models.CharField(blank=True, default='', max_length=50)),
                ('training_year', models.CharField(blank=True, default='', max_length=50)),
                ('session_year', models.CharField(blank=True, default='', max_length=50)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('institution_name', models.CharField(blank=True, default='', max_length=255)),
                ('department_name', models.CharField(blank=True, default='', max_length=255)),
                ('current_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('TRANSFERRED', 'Transferred'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped'), ('SUSPENDED', 'Suspended'), ('UNKNOWN', 'Unknown')], default='ACTIVE', max_length=50)),
                ('pmdc_number', models.CharField(blank=True, help_text='Pakistan Medical & Dental Council registration number', max_length=50, null=True, unique=True)),
                ('university_registration_number', models.CharField(blank=True, default='', max_length=100)),
                ('employee_or_training_id', models.CharField(blank=True, default='', max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('emergency_contact_relation', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_residents', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_residents', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_residents', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='The linked User account representing identity and credentials', on_delete=django.db.models.deletion.PROTECT, related_name='resident_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
