# Generated by Django 5.2.15 on 2026-06-23 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('residents', '0002_residentprofile_department_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='academic_session_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='masters.academicsession'),
        ),
    ]
