# Generated by Django 5.2.15 on 2026-06-23 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET_BY_ADMIN', 'Password Reset by Admin'), ('PROFILE_COMPLETED', 'Profile Completed'), ('PROFILE_UPDATED', 'Profile Updated'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_ACTIVATED', 'User Activated')], help_text='The type of action performed', max_length=50)),
                ('target_model', models.CharField(blank=True, default='', help_text='Name of the model modified, if applicable', max_length=100)),
                ('target_id', models.CharField(blank=True, default='', help_text='ID of the target object modified', max_length=100)),
                ('before', models.JSONField(blank=True, help_text='The state of the object before modification', null=True)),
                ('after', models.JSONField(blank=True, help_text='The state of the object after modification', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra unstructured context metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the requester', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='User-agent of the requester')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the audit log was recorded')),
                ('actor', models.ForeignKey(blank=True, help_text='The user who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
